name: Generate and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Get files
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate documentation
        run: dart doc .

      - name: Upload pages artifacts
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./doc/api

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
  
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
